/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigInteger;

public class Monetary {
    /**
     * The amount of the monetary value.
     */
    @JsonProperty("amount")
    public BigInteger amount;

    public Monetary withAmount(BigInteger amount) {
        this.amount = amount;
        return this;
    }
    
    /**
     * The asset of the monetary value.
     */
    @JsonProperty("asset")
    public String asset;

    public Monetary withAsset(String asset) {
        this.asset = asset;
        return this;
    }
    
    public Monetary(@JsonProperty("amount") BigInteger amount, @JsonProperty("asset") String asset) {
        this.amount = amount;
        this.asset = asset;
  }
}
