/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigInteger;

public class Volume {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("balance")
    public BigInteger balance;

    public Volume withBalance(BigInteger balance) {
        this.balance = balance;
        return this;
    }
    
    @JsonProperty("input")
    public BigInteger input;

    public Volume withInput(BigInteger input) {
        this.input = input;
        return this;
    }
    
    @JsonProperty("output")
    public BigInteger output;

    public Volume withOutput(BigInteger output) {
        this.output = output;
        return this;
    }
    
    public Volume(@JsonProperty("input") BigInteger input, @JsonProperty("output") BigInteger output) {
        this.input = input;
        this.output = output;
  }
}
